spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/employee_dar_db
    username: employee
    password: tracker
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update